### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by malhussein** [zabrewer/FN70489-Scanner#1]
Hello,
First, Thanks a lot for this script, I tried to apply it on 100+ devices, but I get a timeout error from all of them: like:
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-344' coro=<task() done, defined at FN70489-Scanner.py:111> exception=TimeoutError('Host 10.1.1.1 Timeout Error')
>
Traceback (most recent call last):
  File "..........\Python38\lib\site-packages\netdev\vendors\base.py", line 218, in _establish_connec
tion
    self._conn = await asyncio.wait_for(fut, self._timeout)
  File "..........\Python38\lib\asyncio\tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FN70489-Scanner.py", line 112, in task
    async with netdev.create(**param) as ios:
  File "..........\Python38\lib\site-packages\netdev\vendors\base.py", line 185, in __aenter__
    await self.connect()
  File "..........\Python38\lib\site-packages\netdev\vendors\ios_like.py", line 75, in connect
    await self._establish_connection()
  File "..........\Python38\lib\site-packages\netdev\vendors\base.py", line 222, in _establish_connec
tion
    raise TimeoutError(self._host)
netdev.exceptions.TimeoutError: Host 10.1.1.1 Timeout Error

This showing after saying that all devices are reachable and beginning authentication.

Thanks and Best Regards
Muhammad

**Comment by zabrewer** [comment]
Hi Muhammad, I'll take a look - can you split the # of hosts in the YAML file to a smaller # - i.e. test with a few hosts first (3 - 10). and let me know the results?  If 5 hosts in the YAML file still times out back down to say 5 or fewer.  

Also do you use a TACACS server or AAA?

There may be timeout happening if you are using the same credentials on a lot of devices  that use the same TACACS+ server.

Finally, please find this line in the script:


netdev.logger.setLevel(logging.INFO) 

And change it to:


netdev.logger.setLevel(logging.DEBUG)

Then send me the output.

Thanks!

**Comment by zabrewer** [comment]
Also, please post the first few lines of your host YAML file without username/pw/IP (just use scrub and use something generic).

**Comment by malhussein** [comment]
Hi Zabrewer,
Thanks a lot for your help :-) , we are using a TACACS+ server, I tried to reduce the number to three hosts and it worked:
host,ios_version,version affected?,crypto pki found?,certname,number of certname references,found certificate self-signed?,enrollment selfsigned?
10.1.1.1,15.5(3)M4,True,False,,0,,
10.1.1.2,15.5(3)M4,True,False,,0,,
10.1.1.3,15.5(3)M4,True,False,,0,,

So, I guess that the problem must be with the number of hosts & using TACACS+, may be I need to run them in batches, unless there is another way :-)

Thanks and Best Regards,
Muhammad

**Comment by zabrewer** [comment]
Muhammad, I didn't put nearly as much error checking into this project given the timeline - there are a few things you can try:

1) Try to see where the "threshold" is (i.e. 10/20/30/40 etc. hosts per file) for the number of hosts like you tested and back off until you find the right # of hosts per YAML file
2) Change ISE or ACS TACACS attributes (TACACS Profiles in ISE) - this could be difficult because A) you may not have access to your TACACS+ server and B) it may not be a timeout issue in the TACACS+ server itself but rather the backed auth server's response (e.g. AD)
3) play with timers to back off of the connections (speed vs TACACS server connection timeout tradeoff and finding a balance between them).

If you want to test option # 3 above:

1) find the following line:
        show_ver = await ios.send_command("show ver")

and add the following line BEFORE it:
        await asyncio.sleep(5)

(spaces/tabs are important) so it should read:
        await asyncio.sleep(5)
        show_ver = await ios.send_command("show ver")

Experiment with the number sleep.(5) to see if different values make a difference.  I'll try to do some of my own testing ASAP.

**Comment by malhussein** [comment]
Hello Zabrewer,
Thanks a lot for your help, I tried with 50 hosts and it went very well (did not try a bigger number), I also added the command await asyncio.sleep(10), but not sure if it made a difference as it seemed to be working with or without it, however, most of the Routers that failed, failed for other reasons:
- It did not work on VG224 Voice Gateways that use SSH.
- It did not work on any device using Telnet only as an access method.

Thanks a lot for your great support.

Best Regards,
Muhammad :-)

**Comment by zabrewer** [comment]
Yes, I need to do more testing on the thresholds - a queue would be best.  Regarding the VG224s, you may try adding an enable secret to your hosts.YAML file as I mentioned here: https://github.com/zabrewer/FN70489-Scanner/issues/2#issuecomment-569171674

Telnet will not work due to the underlying libraries used - netdev library that I chose because it is written for async (fast) & concurrency depends on another library that is SSH only.  If I can wrap up other issues, I may write a simple telnet version but I am traveling and will have limited access in the next few days.

**Comment by malhussein** [comment]
Thanks a lot, I'm happy with what I have, and I really appreciate your help and support, I checked all the routers I need to check, please enjoy your holidays :-)

**Comment by zabrewer** [comment]
Closing as this issue’s date (01/01/2020). Has passed.  I have an idea for a more flexible and better written scanner that can be used with multiple PSIRTS, EoS, Etc.
